#!/usr/bin/env bash
# 'and' in an if condition
i=1
while [ $i -le 100 ]
do
	if [ $((i%3)) -eq 0 ] && [ $((i%5)) -ne 0 ]
	then
		echo "Fizz"
	elif [ $((i%5)) -eq 0 ] && [ $((i%3)) -ne 0 ]
	then
		echo "Buzz"
	elif [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0 ]
	then
		echo "FizzBuzz"
	else
		echo "$i"
	fi
	i=$((i+1))
done
