#!/usr/bin/env bash
# Display usrName, usrID and home directory path of file

file=$(/etc/passwd)
i=1
read -r n <<< "$(echo "$file" | wc -l)" #count the lines contained in the file to limit the loop

while [ "$i" -le "$n" ]
do

	read -r line <<< "$(head -n $i "$file" | tail -n 1)" #select a line to work on one line at a time

	name=$(echo "$line" | cut -d: -f1)
	id=$(echo "$line" | cut -d: -f3)
	home_dir=$(echo "$line" | cut -d: -f6)

	echo "$name:$id:$home_dir"

	i=$((i+1))
done
